let productsCart = {
    data: [
        //PROMOÇOES ///////////////////////////////////////////////////////////////////////////////////////////////////////////////
      
        //COMPUTADORES//////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        {
            id: 1,
            productName: 'Laptop Pilates 14", touch screen, 12 GB memória',
            category: "Computadores",
            price: '',
            priceP: 516.99,
            image: '/img/computadores/Laptop-Pilates-14-touch-screen-12-GB-memoria.jpg',
        },
        {
            id: 2,
            productName: 'Laptop Pilates 16", touch screen, 24 GB memória',
            category: "Computadores",
            price: "1,099.99",
            priceP: 899.99,
            image: '/img/promocoes/Laptop-Pilates-16touch-screen-24GB-memoria.jpg',
        },
        {
            id: 3,
            productName: 'laptop para games JP 15.6", 512 GB SSD 16GB',
            category: "Computadores",
            price: "1,099.99",
            priceP: 849.99,
            image: '/img/promocoes/laptop-para-gamers-JP-15-512GB.jpg',
        },
        {
            id: 4,
            productName: 'Desktop Corr, 12 GB memória, WiFi, Bluetooth, Teclado, Mouse',
            category: "Computadores",
            price: '',
            priceP: 799.99,
            image: '/img/computadores/Desktop-Corr-12-GB-memória-WiFi-Bluetooth-Teclado-Mouse.jpg',
        },
        {
            id: 5,
            productName: 'Desktop Corr 29", 24 GB memória, Teclado e Mouse',
            category: "Computadores",
            price: '',
            priceP: 1399.99,
            image: '/img/computadores/Desktop-Corr-29-24GB-memória-Teclado-e-Mouse.jpg',
        },
        {
            id: 6,
            productName: 'Laptop Pilates 16", 12 GB memória, touch screen',
            category: "Computadores",
            price: '',
            priceP: 799.99,
            image: '/img/computadores/Laptop-Pilates-16-12GBmemória-touch-screen.jpg',
        },
        {
            id: 7,
            productName: 'Laptop MSP 14", 16 GB memória, cinza',
            category: "Computadores",
            price: '',
            priceP: 849.99,
            image: '/img/computadores/LaptopMSP-14-16GB-memória-cinza.jpg',
        },
        {
            id: 8,
            productName: 'HV- 29" IPS LED FHD FreeSync Monitor JP',
            category: "Computadores",
            price: "269.99",
            priceP: 149.99,
            image: '/img/promocoes/HV-29-IPS-LED-FHD-FreeSync-Monitor-JP.jpg',
        },
        //TABLETS ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        {
            id: 9,
            productName: 'Tablet transparente 10,2", Wi-Fi, 32 GB',
            category: "tablets",
            price: '',
            priceP: 189.99,
            image: '/img/tablets/Tablet-transparente-10,2-Wi-Fi-32GB.jpg',
        },
        {
            id: 10,
            productName: 'Tablet JP - Space 10,4", Wi-Fi, 32 GB',
            category: "tablets",
            price: "329.99",
            priceP: 259.99,
            image: '/img/promocoes/Tablet-JP-Space-10-WI-FI-128GB.jpg',
        },
        {
            id: 11,
            productName: 'Tablet Pilates Go 10.5", touch screen, 64 GB com capa',
            category: "tablets",
            price: '',
            priceP: 479.99,
            image: '/img/tablets/Tablet-Pilates-Go-touch-screen-64-GB-com-capa.jpg',
        },
        {
            id: 12,
            productName: 'Tablet Ove FD Plus 10.3", 64 GB',
            category: "tablets",
            price: "349.99",
            priceP: 249.99,
            image: '/img/promocoes/Tablet-Ove-FD-Plus-10-64GB.jpg',
        },
        {
            id: 13,
            productName: 'Tablet Mini Sheer Pro, 7,9 polegadas',
            category: "tablets",
            price: "100.99",
            priceP: 59.99,
            image: '/img/promocoes/Tablet-Mini-Sheer-Pro-7-polegadas.jpg',
        },
        {
            id: 14,
            productName: 'Tablet Ocean Pro 11 - 12.3", touch screen',
            category: "tablets",
            price: "929.99",
            priceP: 699.99,
            image: '/img/promocoes/Tablet-Ocean-Pro-11-touch-screen.jpg',
        },
        {
            id: 15,
            productName: 'Tablet Corr Playtime 10.3", Wi-Fi, 32 GB',
            category: "tablets",
            price: '',
            priceP: 219.99,
            image: '/img/tablets/Tablet-Corr-Playtime-10-Wi-Fi-32GB.jpg',
        },
        {
            id: 16,
            productName: 'Tablet Space S7 - 11”, 128 GB, Wi-Fi',
            category: "tablets",
            price: '',
            priceP: 899.99,
            image: '/img/tablets/Tablet-Space-S7-11-128GB-Wi-Fi.jpg',
        },
        //Drones-e-cameras////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        {
            id: 17,
            productName: 'Câmera de Segurança Externa Shak Spotlight',
            category: "Drones-e-cameras",
            price: '',
            priceP: 249.99,
            image: '/img/drones-e-cameras/Câmera-de-Segurança-Externa-Shak-Spotlight.jpg',
        },
        {
            id: 18,
            productName: 'Câmera de Segurança de Rede Interna H1C wireless, 1080p',
            category: "Drones-e-cameras",
            price: "379.99",
            priceP: 329.99,
            image: '/img/promocoes/Câmera-de-Segurança-de-Rede-Interna-H1C-wireless-1080p.jpg',
        },
        {
            id: 19,
            productName: 'Quadcopter Wave Mini 4 com controle remoto',
            category: "Drones-e-cameras",
            price: '',
            priceP: 1749.99,
            image: '/img/drones-e-cameras/Quadcopter-Wave-Mini-4-com-controle-remoto.jpg',
        },
        {
            id: 20,
            productName: 'Câmera DSLR Pantony Old School, lente 18-55mm',
            category: "Drones-e-cameras",
            price: "1,699.99",
            priceP: 1299.99,
            image: '/img/promocoes/Camera-DSLR-Pantony-Old-School-lente-18-55mm.jpg',
        },
        {
            id: 21,
            productName: 'Drone Quadcopter HKI Tech, câmera e controle',
            category: "Drones-e-cameras",
            price: '',
            priceP: 579.99,
            image: '/img/mais-vendidos/Drone-Quadcopter-HKI-Tech-câmera-e-controle.jpg',
        },
        {
            id: 22,
            productName: "Câmera digital Mini, À prova d'água, Megapixel",
            category: "Drones-e-cameras",
            price: "699.99",
            priceP: 499.99,
            image: '/img/promocoes/Camera-digital-Mini-a-prova-d-agua-Megapixel.jpg',
        },
        {
            id: 23,
            productName: 'Drone EXE Mini, Controlador Sky',
            category: "Drones-e-cameras",
            price: "",
            priceP: 999.99,
            image: '/img/drones-e-cameras/Drone-EXE-Mini-Controlador-Sky.jpg',
        },
        {
            id: 24,
            productName: 'Câmera digital Pantony 180, 20.0 megapixels',
            category: "Drones-e-cameras",
            price: "",
            priceP: 239.99,
            image: '/img/drones-e-cameras/Camera-digital-Pantony-180-20.0-megapixels.jpg',
        },
        //HEADPHONES//////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        {
            id: 25,
            productName: 'Headphone Balo 700 wireless cancelamento de ruido',
            category: "Headphones",
            price: "329.00",
            priceP: 279.00,
            image: '/img/promocoes/Headphone-Balo-700-wireless-cancelamento-de-ruido.jpg',
        },
        {
            id: 26,
            productName: 'Headphone Space Buds wireless',
            category: "Headphones",
            price: "",
            priceP: 99.99,
            image: '/img/headphones/Headphone-Space-Buds-wireless.jpg',
        },
        {
            id: 27,
            productName: 'Headphone Drums Pro wireless',
            category: "Headphones",
            price: '',
            priceP: 479.99,
            image: '/img/headphones/Headphone-Drums-Pro-wireless.jpg',
        },
        {
            id: 28,
            productName: 'Headphone In-ear wireless, cancelamento de ruído',
            category: "Headphones",
            price: "229.99",
            priceP: 199.99,
            image: '/img/promocoes/Headphone-wireless-cancelamento-de-ruido.jpg',
        },
        {
            id: 29,
            productName: 'Headphone Pantony wireless certificado',
            category: "Headphones",
            price: '',
            priceP: 249.99,
            image: '/img/headphones/Headphone-Pantony-wireless-certificado.jpg',
        },
        {
            id: 30,
            productName: "Headphone branco wireless",
            category: "Headphones",
            price: '',
            priceP: 149.99,
            image: '/img/mais-vendidos/Headphone-branco-wireless.jpg',
        },
        {
            id: 31,
            productName: 'Headset pra games, Surround Sound 10.2',
            category: "Headphones",
            price: "159.55",
            priceP: 129.99,
            image: '/img/promocoes/Headset-pra-games-Surround.jpg',
        },
        {
            id: 32,
            productName: 'Headphone com fio MX50',
            category: "Headphones",
            price: "",
            priceP: 17.99,
            image: '/img/headphones/Headphone-com-fio-MX50.jpg',
        },
        //ALTO-FALANTES///////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        {
            id: 33,
            productName: 'Alto-falante Turn5 portátil com alça e Bluetooth',
            category: "Alto-falantes",
            price: "479.99",
            priceP: 199.99,
            image: '/img/promocoes/Alto-falante-Turn5-portátil-com-alça-e-Bluetooth.jpg',
        },
        {
            id: 34,
            productName: 'Soundbar, Bluetooth, conectividade HDMI-ARC',
            category: "Alto-falantes",
            price: "2,499.99",
            priceP: 1999.99,
            image: '/img/promocoes/Soundbar-Bluetooth-conectividade-HDMI-ARC.jpg',
        },
        {
            id: 35,
            productName: 'Alto-falante Pill Shape portátil, prata, Bluetooth',
            category: "Alto-falantes",
            price: '',
            priceP: 39.99,
            image: '/img/alto-falantes/Alto-falante-Pill-Shape-portátil-prata-Bluetooth.jpg',
        },
        {
            id: 36,
            productName: 'Alto-falante mini, portátil, Bluetooth',
            category: "Alto-falantes",
            price: "129.99",
            priceP: 99.99,
            image: '/img/promocoes/Alto-falante-mini-portátil-Bluetooth.jpg',
        },
        {
            id: 37,
            productName: 'Alto falante Studio 8 portátil, Bluetooth',
            category: "Alto-falantes",
            price: '',
            priceP: 19.99,
            image: '/img/alto-falantes/Alto-falante-Studio-8-portátil-Bluetooth.jpg',
        },
        {
            id: 38,
            productName: 'Alto-falante SDK portátil, Bluetooth',
            category: "Alto-falantes",
            price: '',
            priceP: 549.99,
            image: '/img/alto-falantes/Alto-falante-SDK-portátil-Bluetooth.jpg',
        },
        {
            id: 39,
            productName: 'Alto-falante SXD Mini portátil, Bluetooth',
            category: "Alto-falantes",
            price: '',
            priceP: 219.99,
            image: '/img/alto-falantes/Alto-falante-SXD-Mini-portátil-Bluetooth.jpg',
        },
        {
            id: 40,
            productName: 'Alto-falante portátil Turn5, Bluetooth',
            category: "Alto-falantes",
            price: "129.99",
            priceP: 99.99,
            image: '/img/promocoes/Alto-falante-portátil-Turn5-Bluetooth.jpg',
        },

        //MOBILE///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        {
            id: 41,
            productName: 'Pantony X21 5G, 128 GB, com caneta Z',
            category: "Mobile",
            price: '',
            priceP: 299.99,
            image: '/img/celular/Pantony-X21-5G-128GB-com-caneta-Z.jpg',
        },
        {
            id: 42,
            productName: 'Phantom Exmax JP 5G, 16 GB',
            category: "Mobile",
            price: '',
            priceP: 99.99,
            image: '/img/celular/Phantom-Exmax-JP-5G-16GB.jpg',
        },
        {
            id: 43,
            productName: 'Smartphone Z Pixel Max 128 GB, desbloqueado',
            category: "Mobile",
            price: "449.99",
            priceP: 399.99,
            image: '/img/promocoes/Smartphone-Z-Pixel-Max-128-GB-desbloqueado.jpg',
        },
        {
            id: 44,
            productName: 'OVE Light Space 5G, 128 GB',
            category: "Mobile",
            price: "579.99",
            priceP: 559.99,
            image: '/img/promocoes/OVE-Light-Space-5G-128-GB.jpg',
        },
        {
            id: 45,
            productName: 'Pantony Super 10W 5G, 128 GB',
            category: "Mobile",
            price: '',
            priceP: 599.99,
            image: '/img/celular/Pantony-Super-10W-5G-128-GB.jpg',
        },
        {
            id: 46,
            productName: 'Light Phantom JP, 5g, 256 GB',
            category: "Mobile",
            price: "1,999.99",
            priceP: 899.99,
            image: '/img/promocoes/Light-Phantom-JP-5g-256-GB.jpg',
        },
        {
            id: 47,
            productName: 'Protector XPD Go 5G, 128GB',
            category: "Mobile",
            price: "199.99",
            priceP: 129.99,
            image: '/img/promocoes/Protector-XPD-Go-5G-128GB.jpg',
        },
        {
            id: 48,
            productName: 'Pantony S MAX 5G, 128 GB',
            category: "Mobile",
            price: '',
            priceP: 129.99,
            image: '/img/celular/Pantony-S-MAX-5G-128-GB.jpg',
        },
        //TV-E-HOME-THEATER/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        {
            id: 49,
            productName: 'Smart TV shel 50" UHD 4K LED Class',
            category: "TV-e-home-theater",
            price: '',
            priceP: 349.99,
            image: '/img/mais-vendidos/Smart-TV-shel-50-UHD-4K-LED-Class.jpg',
        },
        {
            id: 50,
            productName: 'Soundbar, Bluetooth, conectividade HDMI-ARC',
            category: "TV-e-home-theater",
            price: "2,499.99",
            priceP: 1999.99,
            image: '/img/promocoes/Soundbar-Bluetooth-conectividade-HDMI-ARC.jpg',
        },
        {
            id: 51,
            productName: 'Smart TV Shel 40" Full HD LED Class',
            category: "TV-e-home-theater",
            price: '',
            priceP: 169.99,
            image: '/img/tv-e-home-theater/Smart-TV-Shel-40-Full-HD-LED-Class.jpg',
        },
        {
            id: 52,
            productName: 'Projetor para Home Theater EPSON 4K PRO-UHD 3LCD',
            category: "TV-e-home-theater",
            price: '',
            priceP: 449.99,
            image: '/img/tv-e-home-theater/Projetor-para-Home-Theater-EPSON-4K-PRO-UHD-3LCD.jpg',
        },
        {
            id: 53,
            productName: 'Smart TV Allure 55" UHD 4K LED Class',
            category: "TV-e-home-theater",
            price: "449.99",
            priceP: 399.99,
            image: '/img/promocoes/Smart-TV-Allure-55-UHD-4K-LED-Class.jpg',
        },
        {
            id: 54,
            productName: 'Projetor Mini Vankyo 470 wireless',
            category: "TV-e-home-theater",
            price: '',
            priceP: 209.99,
            image: '/img/tv-e-home-theater/Projetor-Mini-Vankyo-470-wireless.jpg',
        },
        {
            id: 55,
            productName: 'Smart Streamer TV 42" Class Full HD',
            category: "TV-e-home-theater",
            price: '',
            priceP: 189.99,
            image: '/img/tv-e-home-theater/Smart-Streamer-TV-42-Class-Full-HD.jpg',
        },
        {
            id: 56,
            productName: 'Smart TV 65" UHD 4K LED Class Nano',
            category: "TV-e-home-theater",
            price: "499.99",
            priceP: 459.99,
            image: '/img/mais-vendidos/Smart-TV-65-UHD-4K-LED-Class-Nano.webp',
        },
        //TECNOLOGIA-VESTIVEL///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        {
            id: 57,
            productName: 'Smartwatch Space Moon com carregador',
            category: "Tecnologia-vestivel",
            price: "199.95",
            priceP: 159.95,
            image: '/img/promocoes/Smartwatch-Space-Moon-com-carregador.jpg',
        },
        {
            id: 58,
            productName: 'Fitboot Inspire, tracker de frequência cardíaca',
            category: "Tecnologia-vestivel",
            price: "49.99",
            priceP: 44.99,
            image: '/img/promocoes/Fitboot-Inspire-tracker-de-frequência-cardiaca.jpg',
        },
        {
            id: 59,
            productName: 'Óculos VR Safay GEN 2, 256 GB, controladores de toque',
            category: "Tecnologia-vestivel",
            price: '',
            priceP: 349.99,
            image: '/img/tecnologia-vestivel/Óculos-VR-Safay-GEN-2-256GB-controladores-de-toque.jpg',
        },
        {
            id: 60,
            productName: 'Smartwatch Fitness FitWatch',
            category: "Tecnologia-vestivel",
            price: '',
            priceP: 249.99,
            image: '/img/tecnologia-vestivel/Smartwatch-Fitness-FitWatch.jpg',
        },
        {
            id: 61,
            productName: 'Sistema de Realidade Virtual HV para PC',
            category: "Tecnologia-vestivel",
            price: '',
            priceP: 429.99,
            image: '/img/tecnologia-vestivel/Sistema-de-Realidade-Virtual-HV-para-PC.jpg',
        },
        {
            id: 62,
            productName: 'Rastreador de Atividades Pantony 6P',
            category: "Tecnologia-vestivel",
            price: '',
            priceP: 169.99,
            image: '/img/tecnologia-vestivel/Rastreador-de-Atividades-Pantony-6P.jpg',
        },
        {
            id: 63,
            productName: 'Smartwatch fitness FitWatch XDH',
            category: "Tecnologia-vestivel",
            price: '',
            priceP: 399.99,
            image: '/img/tecnologia-vestivel/Smartwatch-fitness-FitWatch-XDH.jpg',
        },
        {
            id: 64,
            productName: 'Headset de Realidade Virtual Journey Glass Xd',
            category: "Tecnologia-vestivel",
            price: "999.00",
            priceP: 899.99,
            image: '/img/promocoes/Headset-de-Realidade-Virtual-Journey-Glass-Xd.jpg',
        },
//3




    ],
};
let products2 = {
    data : [
        {
            id: 64,
            productName: 'Headset de Realidade Virtual Journey Glass Xd',
            category: "Promoções",
            price: "999.00",
            priceP: 899.99,
            image: '/img/promocoes/Headset-de-Realidade-Virtual-Journey-Glass-Xd.jpg',
        },
        {

            id: 46,
            productName: 'Light Phantom JP, 5g, 256 GB',
            category: "Promoções",
            price: "1.999.99",
            priceP: 899.99,
            image: '/img/promocoes/Light-Phantom-JP-5g-256-GB.jpg',
        },
        {
            id: 63,
            productName: 'Smartwatch Space Moon com carregador',
            category: "Promoções",
            price: "199.95",
            priceP: 159.95,
            image: '/img/promocoes/Smartwatch-Space-Moon-com-carregador.jpg',
        },
        {
            id: 40,
            productName: 'Alto-falante portátil Turn5, Bluetooth',
            category: "Promoções",
            price: "129.99",
            priceP: 99.99,
            image: '/img/promocoes/Alto-falante-portátil-Turn5-Bluetooth.jpg',
        },
        {
            id: 33,
            productName: 'Alto-falante Turn5 portátil com alça e Bluetooth',
            category: "Promoções",
            price: "479.99",
            priceP: 199.99,
            image: '/img/promocoes/Alto-falante-Turn5-portátil-com-alça-e-Bluetooth.jpg',
        },
        {
            id: 50,
            productName: 'Soundbar, Bluetooth, conectividade HDMI-ARC',
            category: "Promoções",
            price: "2,499.99",
            priceP: 1999.99,
            image: '/img/promocoes/Soundbar-Bluetooth-conectividade-HDMI-ARC.jpg',
        },
        {
            id: 20,
            productName: 'Câmera DSLR Pantony Old School, lente 18-55mm',
            category: "Promoções",
            price: "1,699.99",
            priceP: 1299.99,
            image: '/img/promocoes/camera-DSLR-Pantony-Old-School-lente-18-55mm.jpg',
        },
        {
            id: 14,
            productName: 'Tablet Ocean Pro 11 - 12.3", touch screen',
            category: "Promoções",
            price: "929.99",
            priceP: 699.99,
            image: '/img/promocoes/Tablet-Ocean-Pro-11-touch-screen.jpg',
        },
        {
            id: 13,
            productName: 'Tablet Mini Sheer Pro, 7,9 polegadas',
            category: "Promoções",
            price: "100.99",
            priceP: 59.99,
            image: '/img/promocoes/Tablet-Mini-Sheer-Pro-7-polegadas.jpg',
        },
        {
            id: 12,
            productName: 'Tablet Ove FD Plus 10.3", 64 GB',
            category: "Promoções",
            price: "349.99",
            priceP: 249.99,
            image: '/img/promocoes/Tablet-Ove-FD-Plus-10-64GB.jpg',
        },
        {
            id: 2,
            productName: 'Laptop Pilates 16", touch screen, 24 GB memória',
            category: "Promoções",
            price: "1,099.99",
            priceP: 899.99,
            image: '/img/promocoes/Laptop-Pilates-16touch-screen-24GB-memoria.jpg',
        },
        {
            id: 25,
            productName: 'Headphone Balo 700 wireless cancelamento de ruido',
            category: "Promoções",
            price: "329.00",
            priceP: 279.00,
            image: '/img/promocoes/Headphone-Balo-700-wireless-cancelamento-de-ruido.jpg',
        },
        {
            id: 36,
            productName: 'Alto-falante mini, portátil, Bluetooth',
            category: "Promoções",
            price: "129.99",
            priceP: 99.99,
            image: '/img/promocoes/Alto-falante-mini-portátil-Bluetooth.jpg',
        },
        {
            id: 10,
            productName: 'Tablet JP - Space 10,4", WI-FI,128 GB',
            category: "Promoções",
            price: "329.99",
            priceP: 259.99,
            image: '/img/promocoes/Tablet-JP-Space-10-WI-FI-128GB.jpg',
        },
        {
            id: 18,
            productName: 'Câmera de Segurança de Rede Interna H1C wireless, 1080p',
            category: "Promoções",
            price: "379.99",
            priceP: 329.99,
            image: '/img/promocoes/Câmera-de-Segurança-de-Rede-Interna-H1C-wireless-1080p.jpg',
        },
        {
            id: 28,
            productName: 'Headphone in-ear wireless, cancelamento de ruido',
            category: "Promoções",
            price: "229.99",
            priceP: 199.99,
            image: '/img/promocoes/Headphone-wireless-cancelamento-de-ruido.jpg',
        },
        {
            id: 3,
            productName: 'Laptop para games JP 15.6", 512 GB SSD 16GB',
            category: "Promoções",
            price: "1,099.99",
            priceP: 849.99,
            image: '/img/promocoes/laptop-para-gamers-JP-15-512GB.jpg',
        },
        {
            id: 31,
            productName: 'Headset pra games, Surround Sound 10.2',
            category: "Promoções",
            price: "159.55",
            priceP: 129.99,
            image: '/img/promocoes/Headset-pra-games-Surround.jpg',
        },
        {
            id: 22,
            productName: "Câmera digital Mini, Á prova d'água, Megapixel",
            category: "Promoções",
            price: "699.99",
            priceP: 499.99,
            image: '/img/promocoes/Camera-digital-Mini-a-prova-d-agua-Megapixel.jpg',
        },
        {
            id: 53,
            productName: 'Smart TV Allure 55" UHD 4K LED Class',
            category: "Promoções",
            price: "449.99",
            priceP: 399.99,
            image: '/img/promocoes/Smart-TV-Allure-55-UHD-4K-LED-Class.jpg',
        },
        {
            id: 56,
            productName: 'Smart TV 65"UHD 4K LED Class Nano',
            category: "Promoções",
            price: "499.99",
            priceP: 599.99,
            image: '/img/promocoes/Smart-TV-65-UHD-4K-LED-Class-Nano.jpg',
        },
        {
            id: 8,
            productName: 'HV- 29" IPS LED FHD FreeSync Monitor JP',
            category: "Promoções",
            price: "269.99",
            priceP: 149.99,
            image: '/img/promocoes/HV-29-IPS-LED-FHD-FreeSync-Monitor-JP.jpg',
        },
        {
            id: 47,
            productName: 'Protector XPD Go 5G, 128GB',
            category: "Promoções",
            price: 199.99,
            priceP: "129.99",
            image: '/img/promocoes/Protector-XPD-Go-5G-128GB.jpg',
        },
        {
            id: 43,
            productName: 'Smartphone Z Pixel Max 128 GB, desbloqueado',
            category: "Promoções",
            price: "449.99",
            priceP: 399.99,
            image: '/img/promocoes/Smartphone-Z-Pixel-Max-128-GB-desbloqueado.jpg',
        },
        {
            id: 44,
            productName: 'OVE Light Space 5G, 128 GB',
            category: "Promoções",
            price: "579.99",
            priceP: 559.99,
            image: '/img/promocoes/OVE-Light-Space-5G-128-GB.jpg',
        },
        {
            id: 58,
            productName: 'Fitboot Inspire, tracker de frequência cardiaca',
            category: "Promoções",
            price: "49.99",
            priceP: 44.99,
            image: '/img/promocoes/Fitboot-Inspire-tracker-de-frequência-cardiaca.jpg',
        },
        //MAIS VENDIDOS//////////////////////////////////////////////
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        {
            id: 49,
            productName: 'Smart TV shel 50" UHD 4K LED Class',
            category: "Mais-vendidos",
            price: '',
            priceP: 349.99,
            image: '/img/mais-vendidos/Smart-TV-shel-50-UHD-4K-LED-Class.jpg',
        },
        {
            id: 10,
            productName: 'Tablet JP - Space 10,4", Wi-Fi, 32 GB',
            category: "Mais-vendidos",
            price: "329.99",
            priceP: 259.99,
            image: '/img/promocoes/Tablet-JP-Space-10-WI-FI-128GB.jpg',
        },
        {
            id: 58,
            productName: 'Fitboot Inspire, tracker de frequência cardíaca',
            category: "Mais-vendidos",
            price: "49.99",
            priceP: 44.99,
            image: '/img/promocoes/Fitboot-Inspire-tracker-de-frequência-cardiaca.jpg',
        },
        {
            id: 21,
            productName: 'Drone Quadcopter HKI Tech, câmera e controle',
            category: "Mais-vendidos",
            price: '',
            priceP: 579.99,
            image: '/img/mais-vendidos/Drone-Quadcopter-HKI-Tech-câmera-e-controle.jpg',
        },
        {
            id: 38,
            productName: 'Alto-falante SDK portátil, Bluetooth',
            category: "Mais-vendidos",
            price: '',
            priceP: 549.99,
            image: '/img/alto-falantes/Alto-falante-SDK-portátil-Bluetooth.jpg',
        },
        {
            id: 56,
            productName: 'Smart TV 65" UHD 4K LED Class Nano',
            category: "Mais-vendidos",
            price: "499.99",
            priceP: 459.99,
            image: '/img/mais-vendidos/Smart-TV-65-UHD-4K-LED-Class-Nano.webp',
        },
        {
            id: 28,
            productName: 'Headphone In-ear wireless, cancelamento de ruído',
            category: "Mais-vendidos",
            price: "229.99",
            priceP: 199.99,
            image: '/img/promocoes/Headphone-wireless-cancelamento-de-ruido.jpg',
        },
        {
            id: 3,
            productName: 'Laptop para games JP 15.6", 512 GB SSD 16GB',
            category: "Mais-vendidos",
            price: "1,099.99",
            priceP: 849.99,
            image: '/img/promocoes/laptop-para-gamers-JP-15-512GB.jpg',
        },
        {
            id: 22,
            productName: "Câmera digital Mini, À prova d'água, Megapixel",
            category: "Mais-vendidos",
            price: "699.99",
            priceP: 499.99,
            image: '/img/promocoes/Camera-digital-Mini-a-prova-d-agua-Megapixel.jpg',
        },
        {
            id: 30,
            productName: "Headphone branco wireless",
            category: "Mais-vendidos",
            price: '',
            priceP: 149.99,
            image: '/img/mais-vendidos/Headphone-branco-wireless.jpg',
        },
        {
            id: 14,
            productName: 'Tablet Ocean Pro 11 - 12.3", touch screen',
            category: "Mais-vendidos",
            price: "929.99",
            priceP: 699.99,
            image: '/img/promocoes/Tablet-Ocean-Pro-11-touch-screen.jpg',
        },
        {
            id: 43,
            productName: 'Smartphone Z Pixel Max 128 GB, desbloqueado',
            category: "Mais-vendidos",
            price: "449.99",
            priceP: 399.99,
            image: '/img/promocoes/Smartphone-Z-Pixel-Max-128-GB-desbloqueado.jpg',
        },
    ],
}